### ISSUE TITLE
example fails to install and load according to your requirements:

### ISSUE THREAD

**Issue by richlysakowski** [DamianRodziewicz/dash_example#2]
Your example fails to install and load:

03/28/2018  05:38 AM    <DIR>          .
03/28/2018  05:38 AM    <DIR>          ..
03/28/2018  05:38 AM                18 .gitignore
03/28/2018  05:38 AM             1,100 app.py
03/28/2018  05:38 AM             1,639 intermediate_value_app.py
03/28/2018  05:38 AM             1,558 longer_computations_app.py
03/28/2018  05:38 AM               338 README.md
03/28/2018  05:38 AM               469 requirements.txt
               6 File(s)          5,122 bytes
               2 Dir(s)  15,735,963,648 bytes free

(dash_plotly) c:\Users\rlysakow\Desktop\04-GUI-Development-Examples\dashplotly\dash_example_dr

>pip install -r requirements.txt

```
Collecting certifi==2018.1.18
  Using cached certifi-2018.1.18-py2.py3-none-any.whl (151 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click==6.7
  Using cached click-6.7-py2.py3-none-any.whl (71 kB)
Collecting dash==0.21.0
  Using cached dash-0.21.0.tar.gz (15 kB)
Collecting dash-core-components==0.21.0
  Downloading dash_core_components-0.21.0.tar.gz (1.9 MB)
     |████████████████████████████████| 1.9 MB 2.2 MB/s
Collecting dash-html-components==0.9.0
  Downloading dash_html_components-0.9.0.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 759 kB/s
Collecting dash-renderer==0.11.3
  Downloading dash_renderer-0.11.3.tar.gz (126 kB)
     |████████████████████████████████| 126 kB 3.3 MB/s
Collecting decorator==4.2.1
  Using cached decorator-4.2.1-py2.py3-none-any.whl (9.3 kB)
Collecting enum34==1.1.6
  Downloading enum34-1.1.6-py3-none-any.whl (12 kB)
Collecting Flask==0.12.2
  Using cached Flask-0.12.2-py2.py3-none-any.whl (83 kB)
Collecting Flask-Compress==1.4.0
  Using cached Flask-Compress-1.4.0.tar.gz (6.0 kB)
Collecting functools32==3.2.3.post2
  Downloading functools32-3.2.3-2.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\dash_plotly\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rlysakow\\AppData\\Local\\Temp\\pip-install-i0_likf3\\functools32\\setup.py'"'"'; __file__='"'"'C:\\Users\\rlysakow\\AppData\\Local\\Temp\\pip-install-i0_likf3\\functools32\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\rlysakow\AppData\Local\Temp\pip-install-i0_likf3\functools32\pip-egg-info'
         cwd: C:\Users\rlysakow\AppData\Local\Temp\pip-install-i0_likf3\functools32\
    Complete output (1 lines):
    This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by richlysakowski** [comment]
I got it working by installing a completely updated set of packages, as see below. 
The demo runs and I can change in the `figure` data dictionary in the app.py source code file and see the updates to the graphs as a result of the react.js components.

functools is not available yet for Python 3.7  or at least I could not figure out how to install just that package in my environment using pip.  Only the 32-bit functools was available; it gives the error down at the bottom of this posting.

Successfully installed:
attrs-19.3.0
certifi=2019.11.28
chardet==3.0.4
click-7.0
dash-1.9.0
dash-core-components-1.8.0
dash-html-components-1.0.2
dash-renderer-1.2.4
dash-table-4.6.0
decorator-4.4.1
Flask-1.1.1
flask-compress-1.4.0
future-0.18.2
idna-2.8		
importlib-metadata-1.5.0
ipython-genutils-0.2.0
itsdangerous-1.1.0
Jinja2-2.11.1
jsonschema-3.2.0
jupyter-core-4.6.2
MarkupSafe-1.1.1
nbformat-5.0.4
plotly-4.5.0
pytz-2019.3
requests-2.22.0
pywin32-227
pyrsistent-0.15.7
retrying-1.3.3
six-1.14.0
traitlets-4.3.3			
urllib3-1.25.8			
Werkzeug-1.0.0				
zipp-2.2.0


Send2Trash-1.5.0
backcall-0.1.0
bleach-3.1.0
colorama-0.4.3
defusedxml-0.6.0
entrypoints-0.3
ipykernel-5.1.4
ipython-7.12.0
ipywidgets-7.5.1
jedi-0.16.0
jupyter-1.0.0
jupyter-client-5.3.4
jupyter-console-6.1.0
mistune-0.8.4
nbconvert-5.6.1
notebook-6.0.3
pandocfilters-1.4.2
parso-0.6.1
pickleshare-0.7.5
prometheus-client-0.7.1
prompt-toolkit-3.0.3
pygments-2.5.2
python-dateutil-2.8.1
pywinpty-0.5.7
pyzmq-18.1.1
qtconsole-4.6.0
terminado-0.8.3
testpath-0.4.4
tornado-6.0.3
wcwidth-0.1.8
webencodings-0.5.1
widgetsnbextension-3.5.1

##########################
functools wheel compilation error:

pip install functools
```
Collecting functools
  Using cached functools-0.5.tar.gz (4.9 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\dash_plotly\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rlysakow\\AppData\\Local\\Temp\\pip-install-e9lpq9za\\functools\\setup.py'"'"'; __file__='"'"'C:\\Users\\rlysakow\\AppData\\Local\\Temp\\pip-install-e9lpq9za\\functools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\rlysakow\AppData\Local\Temp\pip-install-e9lpq9za\functools\pip-egg-info'
         cwd: C:\Users\rlysakow\AppData\Local\Temp\pip-install-e9lpq9za\functools\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\ProgramData\Anaconda3\envs\dash_plotly\lib\site-packages\setuptools\__init__.py", line 4, in <module>
        import functools
      File "C:\Users\rlysakow\AppData\Local\Temp\pip-install-e9lpq9za\functools\functools.py", line 34
        raise TypeError, 'compose expects at least one argument'
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
